[project]
name = "tiny-llm-convert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.6",
    "safetensors>=0.5.3",
    "torch>=2.7.1",
    "transformers>=4.52.4",
]
